/**
 * Zen System 7.0 - Token Generator
 * Generates src/app/theme.css from src/system/tokens/index.ts
 * 
 * Run: npm run generate:tokens
 */

import fs from 'fs';
import path from 'path';
import { tokens } from '../src/system/tokens';

function toKebabCase(str: string): string {
  return str.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

let cssContent = `/* ============================================================
   GENERATED FILE - DO NOT EDIT DIRECTLY
   Generated by scripts/generate-tokens.ts
   Edit src/system/tokens/index.ts to change values
   ============================================================ */

:root {
`;

// 1. Spacing tokens
Object.entries(tokens.spacing).forEach(([key, value]) => {
  cssContent += `  --space-${key}: ${value};\n`;
});

cssContent += '\n';

// 2. Color tokens
Object.entries(tokens.colors).forEach(([key, value]) => {
  cssContent += `  --color-${toKebabCase(key)}: ${value};\n`;
});

cssContent += '\n';

// 3. Z-Index tokens
Object.entries(tokens.z).forEach(([key, value]) => {
  cssContent += `  --z-${key}: ${value};\n`;
});

cssContent += '\n';

// 4. Layout tokens
Object.entries(tokens.layout).forEach(([key, value]) => {
  cssContent += `  --${toKebabCase(key)}: ${value};\n`;
});

// Add legacy alias for backward compatibility
cssContent += `  --glass-toolbar-rail-width: var(--sidebar-width); /* legacy alias */\n`;

cssContent += '\n';

// 5. Font tokens
Object.entries(tokens.fonts).forEach(([key, value]) => {
  cssContent += `  --font-${key}: ${value};\n`;
});

cssContent += '\n';

// 6. Motion tokens
Object.entries(tokens.motion).forEach(([key, value]) => {
  cssContent += `  --motion-${toKebabCase(key)}: ${value};\n`;
});

cssContent += '\n';

// 7. Gradient tokens
Object.entries(tokens.gradients).forEach(([key, value]) => {
  cssContent += `  --gradient-${toKebabCase(key)}: ${value};\n`;
});

cssContent += '}\n';

// Write the file
const outputPath = path.join(process.cwd(), 'src/app/theme.css');
fs.writeFileSync(outputPath, cssContent);
console.log('✅ Theme CSS generated at src/app/theme.css');
